# Generated by Django 3.2.16 on 2023-01-14 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_type', models.CharField(choices=[('palms', 'Palms'), ('ferns', 'Ferns'), ('indoor_trees', 'Indoor trees'), ('cacti_and_succulents', 'Cacti and Succulents'), ('hydroculture', 'Hydroculture'), ('foliage plants', 'Foliage plants'), ('bonsai', 'Bonsai')], default='palms', max_length=32)),
                ('plant', models.CharField(max_length=255)),
                ('question', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../plant-image_oljnkv', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
